### ISSUE TITLE
enable remote desktop

### ISSUE THREAD

**Issue by Mflixit** [Mflixit/mflixit#11]
in all vms and in master

**Comment by HalfCatTheMan** [comment]
Problem resolved?
Is it my computer's connection to the internet that is now preventing RDC to 101?

**Comment by HalfCatTheMan** [comment]
Tested RDC from another computer outside my network and connected in just fine. Problem seems to be the location of my computer at home. Will change the location of it and try again.

**Comment by Mflixit** [comment]
right click properties on this pc and then remote is on the left
