### ISSUE TITLE
Intermittent Play (For Later) 

### ISSUE THREAD

**Issue by HalfCatTheMan** [Mflixit/mflixit#22]
Streaming starts and stops frequently during playback. Worse on mobile devices.

**Comment by Mflixit** [comment]
can confirm this happens locally after 5 mints

**Comment by HalfCatTheMan** [comment]
1 way i've found to fix this is by lowering the quality of the movie, to what your tv/internet can handle.

**Comment by Mflixit** [comment]
belongs in performence testing
